### ISSUE TITLE
Die Anmeldung ist nur dann erfolgreich, wenn eine gültige TestID angegeben wird und die Anmeldung im Testzeitraum liegt.

### ISSUE THREAD

**Issue by g-baer** [Bello123/togaftest#4]
### Struktur einer TestID
**TestID** ::= Testdatum+Testtyp+IntegerString
**Testdatum** ::= (YYYYMMDD)
**Testtyp** ::= {"Cert"; "Found"; "Full"}
**IntegerString** ::= String(3) ; d.h. zwischen "000" und "999" eine beliebige Zahl
_Beispiel: "20170921Cert020" oder "20191201Full017"_

### Ablaufinformationen
Diese Prüfung erfolgt nach erfolgreicher Überprüfung der Benutzer-Daten. #3 
Wenn die Überprüfung nicht erfolgreich war, soll die Anwendung geschlossen werden.
Wenn die Überprüfung erfolgreich war, soll mit der Prüfung des Test-Status für diesen Benutzer fortgegesetzt werden. #5 

### Voraussetzung
Im Rahmen der Administration wurde ein Test auf den Test-Server geladen.
Der Test ist für einen definierten Zeitraum gültig. 
Die TestID wird den Trainees außerhalb dieser Anwendung vorab per e-Mail verteilt.

**Comment by Bello123** [comment]
Bei fehlerhafter Eingabe wird die Anwendung nicht geschlossen, sonder eine Fehlermeldung zurückgegeben.
Es wird nicht das Format der Eingabe überprüft, nur auf vorhandensein in der DB.
