### ISSUE TITLE
Die Anmeldung ist nur dann erfolgreich, wenn der betreffende Test noch nicht durch den Trainee beendet wurde.

### ISSUE THREAD

**Issue by g-baer** [Bello123/togaftest#5]
Es wird geprüft, ob der Status der Trainee-bezogenen Testdurchführung nicht "submitted" ist.

### Ablaufinformation
Dies ist die erste Prüfung im Rahmen des Login für ein Trainee.
Wenn die Prüfung nicht erfolgreich war, soll die Anwendung geschlossen werden.
Wenn die Prüfung erfolgreich war, dann soll mit der Durchführung des Tests mit der angegbenen TestID forgesetzt werden.

### Voraussetzung
Es gibt ein Feld "Status" zu jedem Trainee für den aktuell laufenden Test. Das Feld kann dabei folgende Werte annehmen:
**Teststatus** ::= ENUM (notStarted; inProgress; submitted)

**Comment by Bello123** [comment]
Prüfung vom Status erst nach der Überprüfung der Nutzerdaten (Id + Passwort) und des Test-Keys (gültiger key, im Zeitraum).
