### ISSUE TITLE
Ein Trainer meldet sich mit TrainerID und PW an.

### ISSUE THREAD

**Issue by g-baer** [Bello123/togaftest#6]
### Struktur einer TrainerID
**BenutzerID** ::= IntegerString+Namenskürzel
**IntegerString** ::= String(8)
**Namenskürzel** ::= String(3) ; erster Buchstabe Vorname + erster Buchstabe Nachname + letzter Buchstabe Nachname
_Beispiel: "08154711LAN" für Lutz Augustin_

### Struktur eines Trainer-PW
Das Passwort ist eine beliebige Kombination von Kleinbuchstaben und Ziffern mit genau 6 Zeichen.
_Beispiel: "ab123u" oder "1qw098z"_

### Ablaufinformationen
Dies ist die einzige Prüfung im Rahmen des Login für einen Trainer.
Wenn die Überprüfung nicht erfolgreich war, soll die Anwendung geschlossen werden.
Wenn die Überprüfung erfolgreich war, soll mit dem Modul "Administration" fortgesetzt werden.

### Voraussetzung
Die Liste von gültigen Trainer ist fest im Code codiert und kann nicht administriert werden. Jede Änderung an dieser Liste ist mit einem Software-Update verbunden. Die Liste besteht derzeit aus folgenden Einträgen:

- TrainerID="08154711LAN" mit PW="qay226"
- TrainerID="10293847KSR" mit PW="d9g7b4"
- TrainerID="98301984TPK" mit PW="3mn8jd"
- TrainerID="39142081FSR" mit PW="p09w6b"
- TrainerID="06318628THN" mit PW="cx34g0"

**Comment by Bello123** [comment]
Nicht fest im Code codiert. Gespeichert in der DB als Hash.

**Comment by Bello123** [comment]
Anwendung wird bei fehleingabe nicht geschlossen. Fehlerausgabe wird ausgegeben
